// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL (transaction pooler) for Supabase - removes pgbouncer query param
    url: process.env["DATABASE_URL"]?.replace("?pgbouncer=true", "") || process.env["DATABASE_URL"],
  },
});
